-- Create bookings table
create table public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null, -- 'iftar' or 'suhoor'
  date date not null,
  time text not null,
  name text not null,
  phone text not null,
  email text not null,
  persons integer default 1,
  notes text,
  status text default 'pending' -- pending, confirmed, cancelled
);

-- Enable RLS
alter table public.bookings enable row level security;

-- Allow public inserts (anyone can book)
create policy "Allow public inserts"
on public.bookings
for insert
to anon
with check (true);

-- Allow admins (service role) to read all
-- (By default service role bypasses RLS, but if we have authenticated admin users later, we need policies)
